Repository btschwertfeger/python-kraken-sdk, pull requests merged in 2023-04, with the labels that each got.

#52 Moved from setup.py only to pyproject.toml
  .gitignore
  MANIFEST.in
  Makefile
  pyproject.toml
  setup.py
Labels: Could

#56 54 add a workflow or jobs that run all tests before a merge is done
  .github/workflows/_test.yml
  .github/workflows/cicd.yml
  .github/workflows/release.yml
Labels: Could

#61 Prepare Release v1.1.0
  .github/codecov.yml
  .github/workflows/_build.yml
  .github/workflows/_build_doc.yml
  .github/workflows/_pypi_publish.yml
  .github/workflows/_test.yml
  .github/workflows/cicd.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  Makefile
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/links.rst
  docs/make.bat
  docs/requirements.txt
  docs/src/about/license.rst
  docs/src/base_api/base_api.rst
  docs/src/examples/futures_bot_template.rst
  docs/src/examples/spot_bot_template.rst
  docs/src/examples/trading_bot_templates.rst
  docs/src/futures/futures_rest.rst
  docs/src/futures/futures_websocket.rst
  docs/src/getting_started/getting_started.rst
  docs/src/introduction.rst
  docs/src/issues.rst
  docs/src/krakenexceptions/krakenexceptions.rst
  docs/src/spot/spot_rest.rst
  docs/src/spot/spot_websocket.rst
  examples/futures_examples.py
  examples/futures_trading_bot_template.py
  examples/futures_ws_examples.py
  examples/spot_examples.py
  examples/spot_trading_bot_template.py
  examples/spot_ws_examples.py
  kraken/base_api/__init__.py
  kraken/exceptions/__init__.py
  kraken/futures/__init__.py
  kraken/futures/funding/__init__.py
  kraken/futures/market/__init__.py
  kraken/futures/trade/__init__.py
  kraken/futures/user/__init__.py
  kraken/futures/websocket/__init__.py
  kraken/futures/ws_client/__init__.py
  kraken/spot/__init__.py
  kraken/spot/funding/__init__.py
  kraken/spot/market/__init__.py
  kraken/spot/staking/__init__.py
  kraken/spot/trade/__init__.py
  kraken/spot/user/__init__.py
  kraken/spot/websocket/__init__.py
  kraken/spot/ws_client/__init__.py
  pyproject.toml
  setup.py
  tests/test_futures_rest.py
  tests/test_spot_rest.py
  tests/test_spot_websocket.py
Labels: Release

#68 Fix and extend release workflow
  .github/workflows/_codecov.yml
  .github/workflows/_test_futures.yml
  .github/workflows/_test_spot.yml
  .github/workflows/cicd.yml
  .github/workflows/release.yml
  README.md
  docs/src/introduction.rst
Labels: Bug, Documentation

#70 Fix PyPI upload job + extend disclaimer
  .github/workflows/_codecov.yml
  .github/workflows/_pypi_publish.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .readthedocs.yaml
  Makefile
  README.md
  docs/conf.py
  docs/src/base_api/base_api.rst
  docs/src/introduction.rst
  pyproject.toml
Labels: Bug, Documentation

#73 Add a Changelog
  .github/workflows/_codeql.yml
  .github/workflows/cicd.yml
  .github/workflows/codeql.yml
  CHANGELOG.md
  Makefile
  README.md
Labels: Documentation

#74 Removed matrix from CodeQL job
  .github/workflows/_codeql.yml
  .github/workflows/release.yml
Labels: CI/CD

#76 Fix bug/typo: "recend" -> recent throughout kraken.spot
  examples/spot_examples.py
  kraken/futures/trade/__init__.py
  kraken/spot/funding/__init__.py
  kraken/spot/market/__init__.py
  tests/spot/test_spot_funding.py
  tests/spot/test_spot_market.py
Labels: Should, Futures, Spot, Breaking

#78 Fixed bug where `spot.user.get_balances` floats to periodic X.9999...
  Makefile
  kraken/spot/user/__init__.py
Labels: Bug, Must, Spot
